name: Check

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: labs/week-12/source
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm ci --prefix api
      - run: npm ci --prefix frontend
      - run: npm test
